### ISSUE TITLE
How does BufferLockManager work?

### ISSUE THREAD

**Issue by OzgurEra** [nvMcJohn/apitest#16]
It looks like doing unnecessary locks.. The procedure looks like this:
Lets say we have 2 ranges.
Range1 and Range2.
Starting:

Check for Range1, not in the locked list, so continue.
Make DrawCall and Add Range1 to lock list.
Check for Range2, not in the locked list, so continue. (Range1's operation on GPU is done here)
Make DrawCall and Add Range2 to lock list.
Check for Range1, it is in the list. So Call glClientWaitSync() and wait for GPU to finish since it is working for Range2. (Unnecessary wait since Range1's operation is done and is not in use)
Make DrawCall and Add Range1 to lock list.
.
.
.

And it will repeat for other ranges too.. and make unnecessary waits. If I'm mistaken,
can someone please explain and help me understand how the procedure actually work.

**Comment by daVinci1980** [comment]
"(Range1's operation on GPU is done here)"

This is not correct. The GPU very likely hasn't seen any of these calls yet, let alone completed them.

"Check for Range1, it is in the list. So Call glClientWaitSync() and wait for GPU to finish since it is working for Range2. (Unnecessary wait since Range1's operation is done and is not in use)"

This is also not correct, because glClientWaitSync is syncing on a specific GLsync, which is the one that is passed in (for range 1). If that operation hasn't completed, then glClientWaitSync will wait for that sync to be signaled. If the operation has completed, glClientWaitSync will simply return. It will not wait for range2's work to complete before signaling. (Although it is entirely possible that Range2 has completed before this point).

**Comment by OzgurEra** [comment]
Oh, I guess I understand now.
So, creating a fence simply locks for the operations BEFORE the creation?
